site_name: "SPAC-CRADLE project"
site_description: "Cascading energy, carbon and water through the soil-plant atmosphere continuum using integrated observations and modelling"
brand: "images/logo/SPAC_CRADLE_2.png"
favicon: "images/logo/SPAC_CRADLE_2.png"
thumbnail: "images/logo/SPAC_CRADLE_2.png"
funding_logo: "images/MICIU+Cofinanciado+AEI.jpg"
author: Esther 
github: CRADLE_web
location:
  department: Tech4Agro
  school: ICA
  university: Consejo Superior de Investigaciones Científicas,Spanish National Research Council,CSIC
  country: Spain
language: en
keywords: 'science, geoscience, geophysics, evapotranspiration, fires, software, open-source'
navigation:
  - name: Home
    id: index
  - name: Team
    id: team/index
  - name: Research
    id: research/index
ignore:
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md
  - contribute.md
  - environment.yml
  - Makefile
  - css/academicons/README.md
  - contribute.md
  

